CREATE TABLE IF NOT EXISTS anecdotalReports (
  id VARCHAR(40) PRIMARY KEY,
  residentId VARCHAR(40) NOT NULL,
  reportDate DATE NOT NULL,
  reportYear INT NOT NULL,
  reportMonth INT NOT NULL,
  room VARCHAR(100) NULL,
  houseparentName VARCHAR(150) NULL,
  content LONGTEXT NOT NULL,
  status ENUM('Draft','Submitted','Under Review','Returned','Finalized') NOT NULL DEFAULT 'Draft',
  createdBy VARCHAR(100) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedBy VARCHAR(100) NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  submittedBy VARCHAR(100) NULL,
  submittedAt DATETIME NULL,
  reviewedBy VARCHAR(100) NULL,
  reviewedAt DATETIME NULL,
  finalizedBy VARCHAR(100) NULL,
  finalizedAt DATETIME NULL,
  reviewNotes TEXT NULL,
  UNIQUE KEY uq_anecdotal_resident_period (residentId, reportYear, reportMonth),
  INDEX idx_anecdotal_resident (residentId),
  INDEX idx_anecdotal_period (reportYear, reportMonth),
  FOREIGN KEY (residentId) REFERENCES children(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
